
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14.0

[window]
decorations = "Buttonless"

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "open"
post_processing = true
mouse = { enabled = true }

# 2. Add the custom VSCode link clicking
[[hints.enabled]]
regex = "vscode://[^\\s]+"
command = "open"
mouse = { enabled = true }
