
[font]
size = 12.0

[window]
decorations = "Buttonless"

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

